export const preview = [
    {id:1,
    location:'Kochi',
    name:'Four points',
    mw:'Mens',
    wifi:true,
    sliderValue:[3750,5750],
    ac: false,
    food:true,
    kitchen:false,
    pets:false,
    abathroom:true,
    sdeposit:true,
    curfew:false,
    hotwater:true,
    balcony:false,
    furnished:true,
    wheelchair:false,
    smoking:false,
    drinking:false,
    student:true,
    proffesional:false,
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
    {id:2,
    location:'Kochi',
    name:'YMCA',
    mw:'Womens',
    wifi:true,
    sliderValue:[5667,8624],
    ac: false,
    food:true,
    kitchen:false,
    pets:false,
    abathroom:true,
    sdeposit:true,
    curfew:true,
    hotwater:true,
    balcony:false,
    furnished:true,
    wheelchair:true,
    smoking:false,
    drinking:false,
    student:true,
    proffesional:true,
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
    {id:3,
    location:'Kochi',
    name:'Churuli',
    mw:'Mens',
    wifi:true,
    sliderValue:[5834,17500],
    ac: false,
    food:false,
    kitchen:true,
    pets:true,
    abathroom:true,
    sdeposit:true,
    curfew:false,
    hotwater:true,
    balcony:true,
    furnished:true,
    wheelchair:false,
    smoking:false,
    drinking:true,
    student:true,
    proffesional:false,
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
    {id:4,
    location:'Kochi',
    name:'Nava Jyothi',
    mw:'Womens',
    wifi:true,
    sliderValue:[4500,5500],
    ac: false,
    food:true,
    kitchen:false,
    pets:false,
    abathroom:true,
    sdeposit:true,
    curfew:true,
    hotwater:true,
    balcony:false,
    furnished:true,
    wheelchair:false,
    smoking:false,
    drinking:false,
    student:true,
    proffesional:true,
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
]